services:
  # prometheus:
  #   image: prom/prometheus:v2.48.0
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yaml'
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  # grafana:
  #   image: grafana/grafana:10.2.2
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
  #     - ./config/grafana/dashboard-platform-overview.json:/var/lib/grafana/dashboards/platform-overview.json
  #     - ./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
  #     - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  discoveryd:
    build: .
    command: discoveryd
    environment:
      PLAT_SERVICE_DISCOVERY_ENABLED: false
      PLAT_SERVICE_REGISTER_INTERVAL: 0
      PLAT_HTTP_SERVER_PORT: 8001
      PLAT_GRPC_SERVER_PORT: 8000
    healthcheck: &healthcheck
      test: ["CMD-SHELL", "curl -f http://localhost:$$PLAT_HTTP_SERVER_PORT/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
      start_interval: 5s

  eventd:
    depends_on: [discoveryd]
    build: .
    command: eventd
    environment:
      PLAT_HTTP_SERVER_PORT: 8003
      PLAT_GRPC_SERVER_PORT: 8004
    healthcheck: *healthcheck

  trafficd:
    depends_on: [discoveryd, eventd]
    build: .
    command: trafficd
    environment:
      PLAT_SERVICE_REGISTER_INTERVAL: 0
      PLAT_HTTP_SERVER_PORT: 8002
    healthcheck: *healthcheck
