services:
  prometheus:
    image: prom/prometheus:v2.43.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    network_mode: "host"
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:9.2.15
    network_mode: "host"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/dashboard-platform-overview.json:/var/lib/grafana/dashboards/platform-overview.json
      - ./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  trafficd:
    build: .
    ports:
      - 8001:8001
    command: trafficd
    environment:
      TRAFFICD_LOG_LEVEL: "info"
      TRAFFICD_HTTP_PORT: 8001
