services:
  prometheus:
    image: prom/prometheus:v2.43.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:9.2.15
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/dashboard-platform-overview.json:/var/lib/grafana/dashboards/platform-overview.json
      - ./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  discoveryd:
    build: .
    command: discoveryd
    environment:
      PLATFORM_HTTP_PORT: 8001
      PLATFORM_GRPC_TLS_CA: "/home/platform/certs/ca.crt.pem"
      PLATFORM_GRPC_SERVER_PORT: 8000
      PLATFORM_GRPC_SERVER_CERT: "/home/platform/certs/server.crt.pem"
      PLATFORM_GRPC_SERVER_KEY: "/home/platform/certs/server.key.pem"

  trafficd:
    build: .
    command: trafficd
    environment:
      PLATFORM_HTTP_PORT: 8002
      PLATFORM_GRPC_TLS_CA: "/home/platform/certs/ca.crt.pem"
      PLATFORM_GRPC_CLIENT_CERT: "/home/platform/certs/client.crt.pem"
      PLATFORM_GRPC_CLIENT_KEY: "/home/platform/certs/client.key.pem"

  eventd:
    build: .
    command: eventd
    environment:
      PLATFORM_HTTP_PORT: 8003
      PLATFORM_GRPC_TLS_CA: "/home/platform/certs/ca.crt.pem"
      PLATFORM_GRPC_SERVER_PORT: 8004
      PLATFORM_GRPC_SERVER_CERT: "/home/platform/certs/server.crt.pem"
      PLATFORM_GRPC_SERVER_KEY: "/home/platform/certs/server.key.pem"
      PLATFORM_GRPC_CLIENT_CERT: "/home/platform/certs/client.crt.pem"
      PLATFORM_GRPC_CLIENT_KEY: "/home/platform/certs/client.key.pem"
