// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/v1/eventd.proto

package pbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Eventd_Event_FullMethodName = "/service.v1.Eventd/Event"
)

// EventdClient is the client API for Eventd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventdClient interface {
	// Event takes host level events.
	Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
}

type eventdClient struct {
	cc grpc.ClientConnInterface
}

func NewEventdClient(cc grpc.ClientConnInterface) EventdClient {
	return &eventdClient{cc}
}

func (c *eventdClient) Event(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, Eventd_Event_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventdServer is the server API for Eventd service.
// All implementations must embed UnimplementedEventdServer
// for forward compatibility
type EventdServer interface {
	// Event takes host level events.
	Event(context.Context, *EventRequest) (*EventResponse, error)
	mustEmbedUnimplementedEventdServer()
}

// UnimplementedEventdServer must be embedded to have forward compatible implementations.
type UnimplementedEventdServer struct {
}

func (UnimplementedEventdServer) Event(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Event not implemented")
}
func (UnimplementedEventdServer) mustEmbedUnimplementedEventdServer() {}

// UnsafeEventdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventdServer will
// result in compilation errors.
type UnsafeEventdServer interface {
	mustEmbedUnimplementedEventdServer()
}

func RegisterEventdServer(s grpc.ServiceRegistrar, srv EventdServer) {
	s.RegisterService(&Eventd_ServiceDesc, srv)
}

func _Eventd_Event_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventdServer).Event(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Eventd_Event_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventdServer).Event(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Eventd_ServiceDesc is the grpc.ServiceDesc for Eventd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Eventd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.v1.Eventd",
	HandlerType: (*EventdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Event",
			Handler:    _Eventd_Event_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/eventd.proto",
}
