name: ci

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    # Run unit tests and linters.
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-cache: true
    - run: make go/test

  proto:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Install protoc
      run: |
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip
        sudo unzip -o protoc-21.12-linux-x86_64.zip -d /usr/local bin/protoc
        sudo unzip -o protoc-21.12-linux-x86_64.zip -d /usr/local 'include/*'

    - run: make proto/check
    #- run: make proto/install
    #- run: make proto/build
    #- run: git diff --exit-code ./pkg/pb
