name: ci

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-cache: true
    - run: make go/test

  proto:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Install protoc
      run: |
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-linux-x86_64.zip
        sudo unzip -o protoc-25.1-linux-x86_64.zip -d /usr/local/bin/protoc
        sudo unzip -o protoc-25.1-linux-x86_64.zip -d /usr/local 'include/*'
    - run: make proto/install
    - run: make proto/check
    - run: make proto/build
    - run: git diff --exit-code ./internal/api
