name: ci

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-cache: true
    - run: make go/test

  docker:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: make tls
    - run: make docker/build

  proto:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - run: make proto/install
    - run: make proto/lint
    - run: make proto/build
    - run: git diff --exit-code ./internal/api
