name: ci

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  cloud:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: cloud
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    # Initialize terraform with no remote state store and
    # validate resources.
    - run: terraform init -backend=false
    - run: terraform fmt -recursive -check
    - run: terraform validate

  service:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: service
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'service/go.mod'

    # Run unit tests and linters.
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-cache: true
        working-directory: service
    - run: make go/test
