name: ci

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  service:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: service
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'service/go.mod'

    # Run unit tests and linters.
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-cache: true
        working-directory: service
    - run: make go/test

  proto:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: service
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'service/go.mod'

    # TODO: install protoc

    #- run: make proto/install
    #- run: make proto/build
    #- run: git diff --exit-code ./pkg/pb
